# Site settings
title: NIEM
# Start with excludes that are as general as is reasonable, and we can make them
# more specific when things don't get exported
# keep this listed sorted alphabetically
exclude:
  - /Makefile
  - /CONTRIBUTING.md
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/Font-Awesome/src
  - vendor/bootstrap/docs
  - "*/aspell-exceptions.txt"
  - "*/Makefile"
  - "*.dot"
  - "*.dot.m4"
  - "*/dot_macros.m4"
  - normative-rules-guidance/country-codes/schema.png
  - json/guidance/aux
  - json/guidance/tmp
  - site-tools

gems:
  - jekyll-mentions
  - jekyll-redirect-from

repository: NIEM/niem.github.io

# Site data
superhero_iepd_path: https://github.com/NIEM/Developer-Network-IEPD-Series--SuperHero
submit_feedback_link: https://github.com/NIEM/NIEM.github.io/issues
niem_comments_link: mailto:niem-comments@lists.gatech.edu

# Build settings
markdown: kramdown

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
